[package]
authors = ["Erik Johnston <erikj@matrix.org>"]
name = "synstatehash"
version = "0.1.0"

[dependencies]
blake2-rfc = "*"
docopt = "*"
postgres_array = "0.6.1"
rustc-serialize = "0.3.18"

[dependencies.postgres]
features = ["unix_socket"]
version = "0.11.4"
